bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-ignore-case on'
bind 'set menu-complete-display-prefix on'
bind 'set colored-completion-prefix on'
bind 'set colored-stats on'
bind 'TAB:menu-complete'
complete -F _complete _

alias ls="eza --icons"
alias la="eza -a --icons"
alias ll="eza -l --icons"
alias lla="eza -la --icons"
alias install="sudo pacman -S"
alias ss="sudo pacman -Ss"
alias rns="sudo pacman -Rns"
alias syu="sudo pacman -Syu"
alias p="paru -S"
alias v="nvim"
alias dv="sudo nvim"
alias fetch="fastfetch ~/.config/fastfetch/art.txt"

BLUE="\e[34m"
GREEN="\e[32m"
YELLOW="\e[33m"
CYAN="\e[36m"
RESET="\e[0m"
WHITE="\e[97m"

PS1="${CYAN}\u${RESET}@${BLUE}\h${RESET}:${GREEN}\w${RESET}$(git_prompt) ${YELLOW}→ ${RESET}"

git_prompt() {
  if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    branch=$(git symbolic-ref --short HEAD 2>/dev/null)
    echo " (${branch})"
  fi
}

pfetch

export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups

setterm -blength 0
